import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './(components)/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Form manager',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex flex-row min-h-screen'>
					<Navbar />
					<div className='flex-grow overflow-y-auto bg-page text-default-text'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}

